/** All texts of the extension (German only, like the app). */
export const t = {
  name: 'Nemo Tresor',
  status: {
    unlocked: 'Verbunden – Tresor entsperrt',
    locked: 'Tresor gesperrt. Entsperre Nemo, dann hier erneut versuchen.',
    appMissing:
      'Nemo wurde nicht gefunden. Starte die Desktop-App und aktiviere dort „Browser-Erweiterung“ (Tresor).',
    pairing: (code: string) =>
      `Bestätige die Verbindung in Nemo (Tresor → Browser-Erweiterung). Code: ${code}`,
    rejected: 'Diese Erweiterung wurde von Nemo nicht zugelassen.',
    checking: 'Verbindung wird geprüft …',
  },
  suggest: {
    title: 'Passwort vorschlagen',
    value: 'Vorgeschlagenes Passwort',
    reroll: 'Neu würfeln',
    use: 'Verwenden',
    settings: 'Einstellungen',
    length: 'Länge',
    lower: 'a–z',
    upper: 'A–Z',
    digits: '0–9',
    symbols: '!@#',
    ambiguous: 'Ähnliche Zeichen vermeiden',
    passphrase: 'Passphrase (Wörter)',
    words: 'Wörter',
    separator: 'Trennzeichen',
    strength: ['Sehr schwach', 'Schwach', 'Mittel', 'Stark', 'Sehr stark'],
    bits: (n: number) => `≈ ${Math.round(n)} Bit`,
    close: 'Schließen',
  },
  save: {
    title: 'Im Tresor speichern?',
    offerTitle: 'Diesen Login im Tresor speichern?',
    updateTitle: 'Passwort aktualisieren?',
    name: 'Name',
    username: 'Benutzername / E-Mail',
    site: 'Seite',
    save: 'Im Tresor speichern',
    update: 'Passwort aktualisieren',
    later: 'Später erinnern',
    discard: 'Verwerfen',
    saved: 'Im Tresor gespeichert.',
    updated: 'Passwort im Tresor aktualisiert.',
    retry: 'Erneut versuchen',
    failed: 'Konnte nicht gespeichert werden.',
    laterHint: 'Ich erinnere dich beim nächsten Seitenaufruf in diesem Tab.',
    kept: 'Bis zum Schließen des Tabs nur im Arbeitsspeicher der Erweiterung.',
  },
  fill: {
    button: 'Aus Nemo ausfüllen',
    title: 'Zugang auswählen',
    none: 'Kein Eintrag für diese Seite.',
    totp: 'Code einfügen',
    filled: 'Ausgefüllt.',
  },
  popup: {
    search: 'Einträge dieser Seite durchsuchen',
    noTab: 'Auf dieser Seite nicht verfügbar.',
    fill: 'Ausfüllen',
    copyUser: 'Benutzername kopieren',
    copyPassword: 'Passwort kopieren',
    copyCode: 'Code kopieren',
    copied: (what: string) => `${what} kopiert – wird nach 30 s gelöscht.`,
    generator: 'Generator',
    generate: 'Neu würfeln',
    copy: 'Kopieren',
    empty: 'Keine Einträge für diese Seite.',
    openSettings: 'Tresor-Einstellungen in Nemo öffnen: Tresor → Browser-Erweiterung',
  },
  errors: {
    generic: 'Das hat nicht geklappt.',
    mismatch: 'Dieser Eintrag gehört nicht zu dieser Seite.',
  },
} as const;
