import {
  Bell,
  Bookmark,
  Cake,
  Copy,
  CloudOff,
  Calendar,
  Check,
  ChevronDown,
  ChevronUp,
  CircleHelp,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Flame,
  GripVertical,
  HardDrive,
  House,
  LayoutGrid,
  ListChecks,
  Lock,
  Luggage,
  Menu,
  Moon,
  Pencil,
  PiggyBank,
  Pin,
  Plus,
  Puzzle,
  Receipt,
  RefreshCw,
  Repeat,
  Search,
  Settings,
  ShoppingCart,
  Sparkles,
  StickyNote,
  Sun,
  Target,
  Trash2,
  Upload,
  Wallet,
  X,
  type LucideIcon,
  Wrench,
  Calculator,
  Percent,
  Coins,
  Timer,
  QrCode,
  Ruler,
  Users,
  CalendarDays,
  Dices,
  Binary,
  Braces,
  Hash,
  Play,
  Pause,
  RotateCcw,
  Globe,
  Image as ImageIcon,
  Type,
  Files,
  Cpu,
  Clock,
  Package,
  Gift,
} from 'lucide-react';

const ICONS = {
  help: CircleHelp,
  disk: HardDrive,
  globe: Globe,
  image: ImageIcon,
  text: Type,
  files: Files,
  cpu: Cpu,
  clock: Clock,
  package: Package,
  gift: Gift,
  home: House,
  calendar: Calendar,
  checklist: ListChecks,
  wallet: Wallet,
  receipt: Receipt,
  repeat: Repeat,
  bell: Bell,
  bookmark: Bookmark,
  note: StickyNote,
  cart: ShoppingCart,
  target: Target,
  piggy: PiggyBank,
  file: FileText,
  cake: Cake,
  luggage: Luggage,
  lock: Lock,
  puzzle: Puzzle,
  settings: Settings,
  grid: LayoutGrid,
  search: Search,
  sparkles: Sparkles,
  plus: Plus,
  pin: Pin,
  more: Ellipsis,
  sun: Sun,
  moon: Moon,
  menu: Menu,
  close: X,
  check: Check,
  trash: Trash2,
  edit: Pencil,
  grip: GripVertical,
  external: ExternalLink,
  eye: Eye,
  eyeOff: EyeOff,
  download: Download,
  copy: Copy,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  upload: Upload,
  flame: Flame,
  sync: RefreshCw,
  cloudOff: CloudOff,
  wrench: Wrench,
  calculator: Calculator,
  percent: Percent,
  coins: Coins,
  timer: Timer,
  qr: QrCode,
  ruler: Ruler,
  users: Users,
  calendarDays: CalendarDays,
  dice: Dices,
  binary: Binary,
  braces: Braces,
  hash: Hash,
  play: Play,
  pause: Pause,
  reset: RotateCcw,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export function Icon({ name, size = 20 }: { name: IconName; size?: number }) {
  const Cmp = ICONS[name] ?? Puzzle;
  return (
    <Cmp size={size} aria-hidden="true" focusable="false" strokeWidth={size < 20 ? 1.75 : 1.5} />
  );
}
