import {
  Bell,
  Bookmark,
  Cake,
  Copy,
  CloudOff,
  Calendar,
  Check,
  ChevronDown,
  ChevronUp,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Flame,
  GripVertical,
  House,
  LayoutGrid,
  ListChecks,
  Lock,
  Luggage,
  Menu,
  Moon,
  Pencil,
  PiggyBank,
  Pin,
  Plus,
  Puzzle,
  Receipt,
  RefreshCw,
  Repeat,
  Search,
  Settings,
  ShoppingCart,
  Sparkles,
  StickyNote,
  Sun,
  Target,
  Trash2,
  Upload,
  Wallet,
  X,
  type LucideIcon,
} from 'lucide-react';

const ICONS = {
  home: House,
  calendar: Calendar,
  checklist: ListChecks,
  wallet: Wallet,
  receipt: Receipt,
  repeat: Repeat,
  bell: Bell,
  bookmark: Bookmark,
  note: StickyNote,
  cart: ShoppingCart,
  target: Target,
  piggy: PiggyBank,
  file: FileText,
  cake: Cake,
  luggage: Luggage,
  lock: Lock,
  puzzle: Puzzle,
  settings: Settings,
  grid: LayoutGrid,
  search: Search,
  sparkles: Sparkles,
  plus: Plus,
  pin: Pin,
  more: Ellipsis,
  sun: Sun,
  moon: Moon,
  menu: Menu,
  close: X,
  check: Check,
  trash: Trash2,
  edit: Pencil,
  grip: GripVertical,
  external: ExternalLink,
  eye: Eye,
  eyeOff: EyeOff,
  download: Download,
  copy: Copy,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  upload: Upload,
  flame: Flame,
  sync: RefreshCw,
  cloudOff: CloudOff,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export function Icon({ name, size = 20 }: { name: IconName; size?: number }) {
  const Cmp = ICONS[name] ?? Puzzle;
  return <Cmp size={size} aria-hidden="true" focusable="false" strokeWidth={1.75} />;
}
