import { useId } from 'react';

/**
 * The Nemo fish (clownfish leaning towards the top-right corner). Source of truth: the master
 * parameters in `design/icon/final.params.mjs`; `npm run export` there writes `web/brand/*.svg`, the
 * block below and the splash in `web/index.html` (`brand-sync.test.ts` keeps the three in step).
 * Decorative by default; pass `title` where the logo is the only label. `mono` draws it in the
 * current text colour (empty states, monochrome contexts).
 */
// brand:begin (generated by design/icon/export-brand.mjs – do not edit by hand)
export const LOGO_PATHS = {
  body: 'M142.7 274.3C165.3 224.4 177.9 173.9 235.8 133.4C307.1 83.5 380.3 87 418.8 142C457.4 197 435.6 267 364.3 316.9C306.4 357.4 254.7 352 200.1 356.2Z',
  tail: 'M162.4 260.5C122.6 288.4 66.1 286.4 56.1 293.4C67.8 341.6 111.2 403.5 152.4 431.1C162.5 424 180 370.3 219.8 342.4Z',
  cut1: 'M262.4 66Q323.3 208.9 436.7 315',
  cut2: 'M173.3 128.4Q244.1 264.3 347.7 377.4',
} as const;
/** Stripe width, eye and corner rounding of the mark, in the same 512 canvas as the paths. */
export const LOGO_CUT_WIDTH = 40;
export const LOGO_EYE = { cx: 370, cy: 146.1, r: 23 } as const;
export const LOGO_SOFTEN = 10;
export const LOGO_COLOR = '#E0550F';
/** Bounding box of the fish inside the 512 canvas. */
export const LOGO_VIEWBOX = '51 93 393 344';
export const LOGO_ASPECT = 1.142;
// brand:end

export function Logo({
  size = 32,
  title,
  mono = false,
}: {
  size?: number;
  title?: string;
  mono?: boolean;
}) {
  const cut = useId();
  const ink = mono ? 'currentColor' : LOGO_COLOR;
  return (
    <svg
      viewBox={LOGO_VIEWBOX}
      height={size}
      width={Math.round(size * LOGO_ASPECT)}
      role={title ? 'img' : undefined}
      aria-label={title}
      aria-hidden={title ? undefined : true}
      focusable="false"
    >
      <defs>
        <mask id={cut} maskUnits="userSpaceOnUse" x="-512" y="-512" width="1536" height="1536">
          <rect x="-512" y="-512" width="1536" height="1536" fill="#fff" />
          <g fill="none" stroke="#000">
            <path d={LOGO_PATHS.cut1} strokeWidth={LOGO_CUT_WIDTH} />
            <path d={LOGO_PATHS.cut2} strokeWidth={LOGO_CUT_WIDTH} />
          </g>
          <circle cx={LOGO_EYE.cx} cy={LOGO_EYE.cy} r={LOGO_EYE.r} fill="#000" />
        </mask>
      </defs>
      <g
        fill={ink}
        stroke={ink}
        strokeWidth={LOGO_SOFTEN}
        strokeLinejoin="round"
        mask={`url(#${cut})`}
      >
        <path d={LOGO_PATHS.body} />
        <path d={LOGO_PATHS.tail} />
      </g>
    </svg>
  );
}
