import wordmarkUrl from '../../brand/logo-wordmark.svg';

/** Aspect ratio of `brand/logo-wordmark.svg` (viewBox 1368 × 401). */
const ASPECT = 1368 / 401;

/**
 * The Nemo wordmark: the lettering drawn as a clownfish (head, a white band in every letter, round
 * tail fin). Same file as the README banner; generated by `design/icon` (`npm run export`). It carries
 * its own colours (logo orange, white bands, dark edges) and works on light and dark surfaces.
 */
export function Wordmark({ height = 28, title }: { height?: number; title?: string }) {
  return (
    <img
      src={wordmarkUrl}
      alt={title ?? ''}
      height={height}
      width={Math.round(height * ASPECT)}
      draggable={false}
      aria-hidden={title ? undefined : true}
    />
  );
}
