// Generated by tools/supporter-cli (`set-public-key`). Public keys only – never a secret.
// Key id → Ed25519 public key (hex). Rotation: add a new id, keep the old ones so old codes stay valid.
// Empty until the maintainer has created the signing key pair (see docs/howto/supporter.md).
export const SUPPORTER_PUBLIC_KEYS: Record<number, string> = {};
