// Generated by tools/supporter-cli (`set-public-key`). Public keys only – never a secret.
// Key id → Ed25519 public key (hex). Rotation: add a new id, keep the old ones so old codes stay valid.
// Id 1 is the maintainer's key (created 2026-10-05; the private key never leaves the maintainer's machine).
export const SUPPORTER_PUBLIC_KEYS: Record<number, string> = {
  1: '46e7ba42f575455902b64eca171ccdd90bdfb437bbaf00c4cec75844a91f67b2',
};
