/** The single place the app reads its public keys from: web/src/core/supporter/publicKeys.ts. */

const ENTRY = /^\s*(\d+):\s*'([0-9a-f]{64})',?\s*$/gm;

export function readPublicKeys(source: string): Record<number, string> {
  const out: Record<number, string> = {};
  for (const m of source.matchAll(ENTRY)) out[Number(m[1])] = m[2]!;
  return out;
}

export function renderPublicKeys(keys: Record<number, string>): string {
  const entries = Object.entries(keys)
    .sort(([a], [b]) => Number(a) - Number(b))
    .map(([id, hex]) => `  ${id}: '${hex}',`)
    .join('\n');
  return `// Generated by tools/supporter-cli (\`set-public-key\`). Public keys only – never a secret.
// Key id → Ed25519 public key (hex). Rotation: add a new id, keep the old ones so old codes stay valid.
export const SUPPORTER_PUBLIC_KEYS: Record<number, string> = {
${entries}${entries ? '\n' : ''}};
`;
}
