// Writes the brand sources from the master parameters (final.params.mjs):
//   web/brand/*.svg, the marked block in web/src/ui/Logo.tsx, the splash in web/index.html.
// Then render the rasters: cd web && npx tauri icon brand/app-icon.svg && npm run gen:icons
//
//   node export-brand.mjs            (npm run export)
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { markGeometry } from './fish.mjs';
import { buildWordmark } from './wordmark.mjs';
import { ICON, MASKABLE_SAFE_RADIUS, WORDMARK } from './final.params.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const web = resolve(here, '../../web');
const g = markGeometry(ICON);
const [c1, c2] = g.cuts;
if (c1.w !== c2.w) throw new Error('both stripes must share one width (Logo.tsx has a single constant)');
const r1 = (n) => Math.round(n * 10) / 10;
const r3 = (n) => Math.round(n * 1000) / 1000;

const OWN = ICON.mark.colors.body; // logo orange
const WHITE = '#FFFFFF';
const { cx, cy, r } = g.eye;

const mask = (id) =>
  `<mask id="${id}" maskUnits="userSpaceOnUse" x="-512" y="-512" width="1536" height="1536">
      <rect x="-512" y="-512" width="1536" height="1536" fill="#fff"/>
      <g fill="none" stroke="#000">
        <path d="${c1.d}" stroke-width="${c1.w}"/>
        <path d="${c2.d}" stroke-width="${c2.w}"/>
      </g>
      <circle cx="${cx}" cy="${cy}" r="${r}" fill="#000"/>
    </mask>`;
/** Fish with stripes and eye cut out; the stroke in the same colour rounds the corners. */
const fish = (color, id, indent = '  ') =>
  `${indent}<g fill="${color}" stroke="${color}" stroke-width="${g.soften}" stroke-linejoin="round" mask="url(#${id})">
${indent}  <path d="${g.body}"/>
${indent}  <path d="${g.tail}"/>
${indent}</g>`;
const svg = (viewBox, inner, label = true) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}"${label ? ' role="img" aria-label="Nemo"' : ''}>\n${inner}\n</svg>\n`;
/** translate + scale that equals "scale s around (256,256), then move by (dx, dy)". */
const place = (s, dx = 0, dy = 0) => `translate(${r3(256 * (1 - s) + dx)} ${r3(256 * (1 - s) + dy)}) scale(${s})`;

// Tight view box around the fish (mark, Logo.tsx, splash); square box for the one-colour file.
const b = g.bbox;
const tight = [Math.floor(b.x), Math.floor(b.y), Math.ceil(b.w) + 1, Math.ceil(b.h) + 1];
const side = Math.ceil(Math.max(b.w, b.h) * 1.08);
const square = [r1(b.x + b.w / 2 - side / 2), r1(b.y + b.h / 2 - side / 2), side, side];

const files = {};
files['logo-mark.svg'] = svg(
  tight.join(' '),
  `  <!-- Nemo mark: one fill, stripes and eye are cut out (mask) so it sits on any background. -->
  <defs>
    ${mask('nemo-mark-cut')}
  </defs>
${fish(OWN, 'nemo-mark-cut')}`,
);
files['logo-mono.svg'] = svg(
  square.join(' '),
  `  <defs>
    ${mask('nemo-mono-cut')}
  </defs>
${fish('#000', 'nemo-mono-cut')}`,
);
const plate = ICON.plate;
files['app-icon.svg'] = svg(
  '0 0 512 512',
  `  <defs>
    ${mask('nemo-app-cut')}
  </defs>
  <rect width="512" height="512" rx="${plate.radius}" fill="${plate.fill}"/>
  <g transform="${place(plate.scale, plate.dx, plate.dy)}">
${fish(WHITE, 'nemo-app-cut', '    ')}
  </g>`,
);
const safe = Math.min(1, MASKABLE_SAFE_RADIUS / g.radius(1));
files['app-icon-maskable.svg'] = svg(
  '0 0 512 512',
  `  <defs>
    ${mask('nemo-maskable-cut')}
  </defs>
  <rect width="512" height="512" fill="${plate.fill}"/>
  <g transform="${place(r3(safe))}">
${fish(WHITE, 'nemo-maskable-cut', '    ')}
  </g>`,
);
const ad = ICON.adaptive;
const ADAPTIVE_SAFE = 156.4; // 66 dp of the 108 dp canvas, in the 512 box
if (g.radius(ad.scale, ad.dx, ad.dy) > ADAPTIVE_SAFE) throw new Error('adaptive layer leaves the safe zone');
files['android-foreground.svg'] = svg(
  '0 0 512 512',
  `  <defs>
    ${mask('nemo-fg-cut')}
  </defs>
  <g transform="${place(ad.scale, ad.dx, ad.dy)}">
${fish(WHITE, 'nemo-fg-cut', '    ')}
  </g>`,
  false,
);
files['android-monochrome.svg'] = svg(
  '0 0 512 512',
  `  <defs>
    ${mask('nemo-monochrome-cut')}
  </defs>
  <g transform="${place(ad.scale, ad.dx, ad.dy)}">
${fish('#fff', 'nemo-monochrome-cut', '    ')}
  </g>`,
  false,
);
files['logo-wordmark.svg'] = buildWordmark(WORDMARK.concept, WORDMARK.params, 'light');
files['logo-wordmark-light.svg'] = buildWordmark(WORDMARK.concept, WORDMARK.params, 'dark');
for (const [name, text] of Object.entries(files)) writeFileSync(join(web, 'brand', name), text);

// ---- Logo.tsx: constants between the markers ----------------------------------------------
const block = `// brand:begin (generated by design/icon/export-brand.mjs – do not edit by hand)
export const LOGO_PATHS = {
  body: '${g.body}',
  tail: '${g.tail}',
  cut1: '${c1.d}',
  cut2: '${c2.d}',
} as const;
/** Stripe width, eye and corner rounding of the mark, in the same 512 canvas as the paths. */
export const LOGO_CUT_WIDTH = ${c1.w};
export const LOGO_EYE = { cx: ${cx}, cy: ${cy}, r: ${r} } as const;
export const LOGO_SOFTEN = ${g.soften};
export const LOGO_COLOR = '${OWN}';
/** Bounding box of the fish inside the 512 canvas. */
export const LOGO_VIEWBOX = '${tight.join(' ')}';
export const LOGO_ASPECT = ${r3(tight[2] / tight[3])};
// brand:end`;
const replaceBlock = (file, re, text) => {
  const path = join(web, file);
  const src = readFileSync(path, 'utf8');
  if (!re.test(src)) throw new Error(`markers missing in ${file}`);
  writeFileSync(path, src.replace(re, () => text));
};
replaceBlock('src/ui/Logo.tsx', /\/\/ brand:begin[\s\S]*?\/\/ brand:end/, block);

// ---- index.html splash ------------------------------------------------------------------
const splash = `<!-- brand:begin -->
      <svg viewBox="${tight.join(' ')}" focusable="false">
        <defs>
          ${mask('sp')}
        </defs>
        <g fill="${OWN}" stroke="${OWN}" stroke-width="${g.soften}" stroke-linejoin="round" mask="url(#sp)">
          <path d="${g.body}" />
          <path d="${g.tail}" />
        </g>
      </svg>
      <!-- brand:end -->`;
replaceBlock('index.html', /<!-- brand:begin -->[\s\S]*?<!-- brand:end -->/, splash);

console.log(`brand sources written; fish viewBox ${tight.join(' ')}, maskable scale ${r3(safe)}`);
console.log(`adaptive radius ${r1(g.radius(ad.scale, ad.dx, ad.dy))} of ${ADAPTIVE_SAFE}`);
