/**
 * German texts of the Dev-Preview tooling (test data). Kept out of `strings.ts` on purpose: only
 * dev-only code imports this file, so stable builds contain none of it (`core/seed/devFlag.test.ts`).
 */
export const tDev = {
  title: 'Entwickler',
  intro:
    'Nur in der Dev-Preview. Testdaten sind erfunden, bleiben auf diesem Gerät (kein Sync, kein Backup) und lassen sich jederzeit wieder entfernen.',
  load: {
    scale: 'Umfang',
    small: 'Klein (zum Ausprobieren)',
    medium: 'Mittel (Standard)',
    large: 'Groß (Performance, ca. 5.000 Buchungen)',
    button: 'Testdaten laden',
    busy: (done: number, total: number) => `Lade … ${done} von ${total}`,
    done: (n: number) => `Testdaten geladen (${n} Einträge).`,
    error: 'Testdaten konnten nicht geladen werden.',
  },
  remove: {
    button: 'Testdaten entfernen',
    hint: 'Entfernt nur die erzeugten Testdaten, deine eigenen Daten bleiben.',
    done: (n: number) => `${n} Testeinträge entfernt.`,
  },
  reset: {
    title: 'Alles zurücksetzen',
    hint: 'Löscht die komplette lokale Datenbank dieses Geräts (auch eigene Daten, Einstellungen, Schlüssel). Tippe zur Bestätigung ZURÜCKSETZEN.',
    phrase: 'ZURÜCKSETZEN',
    field: 'Bestätigung',
    button: 'Alles zurücksetzen',
  },
  sync: {
    label: 'Seed-Sync erlauben',
    hint: 'Standard aus: Testdaten gelangen nicht auf den Sync-Server. Wenn du das einschaltest, werden sie wie echte Daten übertragen. Beim Entfernen werden sie dann auch auf dem Server gelöscht.',
  },
  status: {
    title: 'Stand',
    version: 'Seed-Version',
    reference: 'Referenzdatum',
    scale: 'Umfang',
    none: 'Keine Testdaten geladen.',
    entries: 'Einträge',
    demoVault: (phrase: string) =>
      `Demo-Tresor (Modul Accounts): Passphrase „${phrase}“. Ein vorhandener Tresor wird nie überschrieben.`,
  },
  banner: {
    text: 'Testdaten geladen, entfernen unter Einstellungen → Entwickler.',
    open: 'Zu den Einstellungen',
    dismiss: 'Verstanden',
    label: 'Hinweis zu Testdaten',
  },
  palette: {
    load: 'Testdaten laden',
    remove: 'Testdaten entfernen',
    loaded: 'Testdaten geladen.',
    removed: 'Testdaten entfernt.',
  },
  components: {
    title: 'Komponentenblatt',
    intro:
      'Alle gemeinsamen Bausteine auf einer Seite (nur Dev-Preview und E2E-Build). Daten sind erfunden.',
    buttons: 'Buttons',
    primary: 'Primär (einmal pro Ansicht)',
    secondary: 'Sekundär',
    quiet: 'Ruhig',
    danger: 'Löschen bestätigen',
    quietDanger: 'Löschen',
    small: 'Klein',
    disabled: 'Deaktiviert',
    iconButton: 'Bearbeiten',
    fields: 'Felder',
    name: 'Name',
    nameHint: 'So steht es in der Liste.',
    nameError: 'Bitte einen Namen eingeben.',
    account: 'Konto',
    accountOne: 'Girokonto',
    accountTwo: 'Sparkonto',
    due: 'Fällig am',
    note: 'Notiz',
    checkbox: 'Mit Erinnerung',
    switchLabel: 'Automatisch sperren',
    choices: 'Auswahl',
    view: 'Ansicht',
    month: 'Monat',
    week: 'Woche',
    chipOne: 'Alle',
    chipTwo: 'Offen',
    chipThree: 'Bezahlt',
    tabs: 'Reiter',
    tabsLabel: 'Beispielreiter',
    tabA: 'Übersicht',
    tabB: 'Rechnungen',
    tabC: 'Abos',
    cards: 'Karte',
    cardTitle: 'Kontostand',
    cardBody: 'Eine Karte gruppiert nur: Schatten statt Rahmen.',
    rows: 'Zeilen',
    rowsLabel: 'Beispielzeilen',
    rowOne: 'Stadtwerke Musterstadt',
    rowOneMeta: 'Fällig am Do., 1. Okt. · SW-2026-1000',
    rowTwo: 'Zahnarztpraxis Dr. Beispiel',
    rowTwoMeta: 'Überfällig seit 26. Sep.',
    rowThree: 'Internet & Telefon',
    rowThreeMeta: 'Bezahlt am 20. Sep.',
    amount: '87,40 €',
    swipeDone: 'Bezahlt',
    swipeLater: 'Später',
    delete: 'Zeile löschen',
    selectionActions: 'Erledigt',
    badges: 'Abzeichen',
    badgeEvent: 'Termin',
    badgeReminder: 'Erinnerung',
    badgeOverdue: 'überfällig',
    badgePaid: 'bezahlt',
    badgeExpiring: 'läuft ab',
    badgeInfo: 'Beta',
    states: 'Zustände',
    progress: 'Fortschritt',
    progressLabel: 'Budget verbraucht',
    empty: 'Noch nichts da.',
    emptyAction: 'Anlegen',
    error: 'Das hat nicht geklappt.',
    feedback: 'Rückmeldung',
    toast: 'Toast zeigen',
    toastMessage: 'Als bezahlt markiert.',
    toastUndo: 'Toast mit Rückgängig',
    toastUndone: 'Zurückgenommen.',
    dialog: 'Dialog',
    openDialog: 'Dialog öffnen',
    dialogTitle: 'Neuer Eintrag',
    dialogHint:
      'Tippe etwas und schließe mit Esc: du wirst gefragt, ob der Entwurf verworfen werden soll.',
    save: 'Speichern',
  },
} as const;
