/** All user-facing German UI text lives here (i18n-ready later). */
export const t = {
  appName: 'Taschenmesser',
  nav: {
    dashboard: 'Übersicht',
    library: 'Modul-Bibliothek',
    settings: 'Einstellungen',
    more: 'Mehr',
    main: 'Hauptnavigation',
    skipToContent: 'Zum Inhalt springen',
  },
  actions: {
    add: 'Hinzufügen',
    quickAdd: 'Schnell hinzufügen',
    search: 'Suchen',
    cancel: 'Abbrechen',
    save: 'Speichern',
    delete: 'Löschen',
    edit: 'Bearbeiten',
    close: 'Schließen',
    enable: 'Aktivieren',
    disable: 'Deaktivieren',
    reload: 'Neu laden',
    update: 'Aktualisieren',
  },
  dashboard: {
    title: 'Übersicht',
    emptyTitle: 'Noch keine Module aktiv',
    emptyText: 'Aktiviere Module in der Bibliothek, um hier Widgets zu sehen.',
    toLibrary: 'Zur Bibliothek',
    noWidgets: 'Die aktiven Module bieten keine Widgets an.',
  },
  library: {
    title: 'Modul-Bibliothek',
    intro: 'Aktiviere nur, was du brauchst. Deaktivierte Module bleiben unsichtbar.',
    active: 'Aktiv',
    inactive: 'Inaktiv',
    disableTitle: (name: string) => `„${name}“ deaktivieren?`,
    disableText: 'Was soll mit den gespeicherten Daten dieses Moduls passieren?',
    keepData: 'Daten behalten (ausgeblendet)',
    keepDataHint: 'Bei erneutem Aktivieren ist alles wieder da.',
    deleteData: 'Daten löschen',
    deleteDataHint: 'Alle Einträge dieses Moduls werden entfernt.',
    devOnly: 'Entwickler',
  },
  settings: {
    title: 'Einstellungen',
    appearance: 'Darstellung',
    theme: 'Farbschema',
    themeSystem: 'System',
    themeLight: 'Hell',
    themeDark: 'Dunkel',
    modules: 'Module',
    noModuleSettings: 'Aktive Module haben keine eigenen Einstellungen.',
  },
  palette: {
    title: 'Befehlspalette',
    placeholder: 'Suchen oder springen zu …',
    empty: 'Keine Treffer',
    hint: 'Ctrl+K',
  },
  quickAdd: {
    title: 'Schnell hinzufügen',
    empty: 'Aktive Module bieten noch keine Schnellaktionen an.',
  },
  pwa: {
    updateAvailable: 'Eine neue Version ist verfügbar.',
    offlineReady: 'Bereit für die Offline-Nutzung.',
  },
  errors: {
    notFound: 'Seite nicht gefunden',
    moduleDisabled: 'Dieses Modul ist nicht aktiv.',
    generic: 'Etwas ist schiefgelaufen.',
  },
  form: {
    title: 'Titel',
    note: 'Notiz',
    date: 'Datum',
    time: 'Uhrzeit',
    required: 'Bitte ausfüllen',
    confirmDelete: 'Wirklich löschen?',
  },
  recurrence: {
    label: 'Wiederholung',
    none: 'Keine',
    daily: 'Täglich',
    weekly: 'Wöchentlich',
    monthly: 'Monatlich',
    yearly: 'Jährlich',
    every: 'Alle',
    daysUnit: 'Tage',
    weeksUnit: 'Wochen',
    monthsUnit: 'Monate',
    yearsUnit: 'Jahre',
    weekdays: 'Wochentage',
    monthDay: 'Tag des Monats',
    lastDay: 'Letzter Tag',
    ends: 'Ende',
    endsNever: 'Nie',
    endsOn: 'Am Datum',
    endsAfter: 'Nach Anzahl',
    endDate: 'Enddatum',
    count: 'Anzahl',
  },
  todos: {
    title: 'ToDos',
    add: 'ToDo hinzufügen',
    addPlaceholder: 'Neue Aufgabe …',
    empty: 'Nichts zu tun – gut so.',
    allOpen: 'Alle offenen',
    newList: 'Neue Liste',
    listName: 'Listenname',
    renameList: 'Liste umbenennen',
    deleteList: 'Liste löschen',
    deleteListHint: 'Die Liste und alle ihre Aufgaben werden gelöscht.',
    inbox: 'Eingang',
    list: 'Liste',
    priority: 'Priorität',
    prio: ['Keine', 'Niedrig', 'Mittel', 'Hoch'],
    due: 'Fällig am',
    noDue: 'Ohne Datum',
    subtasks: 'Unteraufgaben',
    addSubtask: 'Unteraufgabe hinzufügen',
    editTask: 'Aufgabe bearbeiten',
    showDone: 'Erledigte anzeigen',
    overdue: 'Überfällig',
    openCount: (n: number) => (n === 1 ? '1 offene Aufgabe' : `${n} offene Aufgaben`),
    widgetEmpty: 'Keine offenen Aufgaben',
    progress: (done: number, total: number) => `${done}/${total}`,
  },
  calendar: {
    title: 'Kalender',
    today: 'Heute',
    month: 'Monat',
    week: 'Woche',
    day: 'Tag',
    view: 'Ansicht',
    prev: 'Zurück',
    next: 'Weiter',
    newEvent: 'Neuer Termin',
    editEvent: 'Termin bearbeiten',
    allDay: 'Ganztägig',
    start: 'Beginn',
    end: 'Ende',
    location: 'Ort',
    nothing: 'Keine Einträge',
    endBeforeStart: 'Das Ende darf nicht vor dem Beginn liegen.',
    more: (n: number) => `+${n} weitere`,
    widgetTitle: 'Heute & Morgen',
    widgetEmpty: 'Nichts geplant.',
    week_: (n: number) => `KW ${n}`,
    kinds: {
      event: 'Termin',
      task: 'ToDo',
      reminder: 'Erinnerung',
      invoice: 'Rechnung',
      subscription: 'Abo',
      cancel: 'Kündigung',
    } as Record<string, string>,
  },
  reminders: {
    title: 'Erinnerungen',
    add: 'Erinnerung hinzufügen',
    edit: 'Erinnerung bearbeiten',
    empty: 'Noch keine Erinnerungen.',
    firstDate: 'Erster Termin',
    next: 'Nächste',
    ended: 'Beendet',
    paused: 'Pausiert',
    active: 'Aktiv',
    widgetTitle: 'Nächste Erinnerungen',
    widgetEmpty: 'Keine anstehenden Erinnerungen.',
  },
  notifications: {
    title: 'Benachrichtigungen',
    intro:
      'Erinnerungen erscheinen als Benachrichtigung, solange die App geöffnet ist oder im Hintergrund läuft. Bei geschlossener App sind sie nicht zuverlässig.',
    enable: 'Benachrichtigungen aktivieren',
    granted: 'Aktiviert',
    denied: 'Blockiert – bitte in den Browser-Einstellungen für diese Seite erlauben.',
    default: 'Noch nicht aktiviert',
    unsupported: 'Wird von diesem Browser nicht unterstützt.',
    test: 'Testbenachrichtigung senden',
    testBody: 'Es funktioniert.',
  },
  dashboardEdit: {
    customize: 'Anpassen',
    done: 'Fertig',
    hide: 'Ausblenden',
    show: 'Einblenden',
    handle: (title: string) => `${title} verschieben`,
    hidden: 'Ausgeblendet',
    instructions:
      'Zum Verschieben Leertaste drücken, mit den Pfeiltasten bewegen und mit der Leertaste ablegen. Esc bricht ab.',
    picked: (title: string) => `${title} aufgenommen.`,
    moved: (title: string, pos: number) => `${title} auf Position ${pos} verschoben.`,
    dropped: (title: string, pos: number) => `${title} auf Position ${pos} abgelegt.`,
    cancelled: 'Verschieben abgebrochen.',
  },
  money: {
    amount: 'Betrag',
    invalidAmount: 'Bitte einen gültigen Betrag eingeben, z. B. 12,50',
  },
  invoices: {
    title: 'Rechnungen',
    add: 'Rechnung hinzufügen',
    edit: 'Rechnung bearbeiten',
    payee: 'Empfänger',
    reference: 'Verwendungszweck / Rechnungsnummer',
    dueDate: 'Fällig am',
    paidAt: 'Bezahlt am',
    open: 'Offen',
    paid: 'Bezahlt',
    markPaid: 'Als bezahlt markieren',
    markedPaid: 'Als bezahlt markiert.',
    reopen: 'Wieder öffnen',
    undo: 'Rückgängig',
    empty: 'Keine offenen Rechnungen.',
    emptyPaid: 'Noch keine bezahlten Rechnungen.',
    openTotal: 'Offen gesamt',
    overdue: 'Überfällig',
    widgetEmpty: 'Keine offenen Rechnungen.',
    openCount: (n: number) => (n === 1 ? '1 offene Rechnung' : `${n} offene Rechnungen`),
    view: 'Status',
  },
  subscriptions: {
    title: 'Abos',
    add: 'Abo hinzufügen',
    edit: 'Abo bearbeiten',
    name: 'Name',
    firstCharge: 'Abbuchung am',
    firstChargeHint: 'Ein bekanntes Abbuchungsdatum – daraus ergeben sich die weiteren.',
    noticeDays: 'Kündigungsfrist (Tage vor Abbuchung)',
    noticeHint: 'Leer lassen, wenn jederzeit kündbar.',
    active: 'Aktiv',
    paused: 'Pausiert',
    empty: 'Noch keine Abos.',
    perMonth: 'Pro Monat',
    perYear: 'Pro Jahr',
    perMonthShort: 'pro Monat',
    nextCharge: 'Nächste Abbuchung',
    cancelBy: 'Kündigen bis',
    ended: 'Beendet',
    every: 'Intervall',
    widgetEmpty: 'Keine aktiven Abos.',
    monthlyCost: (v: string) => `≙ ${v} pro Monat`,
  },
  finance: {
    title: 'Finanzen',
    balance: 'Kontostand',
    available: 'Verfügbar',
    tabs: {
      overview: 'Übersicht',
      transactions: 'Buchungen',
      accounts: 'Konten',
      categories: 'Kategorien',
    },
    tabsLabel: 'Bereich',
    month: 'Monat',
    currentMonth: 'Aktueller Monat',
    prevMonth: 'Vorheriger Monat',
    nextMonth: 'Nächster Monat',
    income: 'Einnahmen',
    expense: 'Ausgaben',
    net: 'Saldo',
    incomeOne: 'Einnahme',
    expenseOne: 'Ausgabe',
    kind: 'Art',
    breakdown: (balance: string, invoices: string, subs: string) =>
      [
        `Kontostand ${balance}`,
        invoices && `offene Rechnungen −${invoices}`,
        subs && `Abos bis Monatsende −${subs}`,
      ]
        .filter(Boolean)
        .join(' · '),
    expensesByCategory: 'Ausgaben nach Kategorie',
    trend: 'Einnahmen und Ausgaben der letzten 6 Monate',
    showTable: 'Als Tabelle anzeigen',
    showChart: 'Als Diagramm anzeigen',
    tableShort: 'Tabelle',
    chartShort: 'Diagramm',
    addTransactionShort: 'Buchung',
    noExpenses: 'Keine Ausgaben in diesem Monat.',
    category: 'Kategorie',
    amount: 'Betrag',
    month_: 'Monat',
    addTransaction: 'Buchung hinzufügen',
    editTransaction: 'Buchung bearbeiten',
    noTransactions: 'Keine Buchungen in diesem Monat.',
    payee: 'Empfänger / Titel',
    account: 'Konto',
    noCategory: 'Ohne Kategorie',
    fromInvoice: 'Automatisch aus einer bezahlten Rechnung gebucht.',
    addAccount: 'Konto hinzufügen',
    editAccount: 'Konto bearbeiten',
    accountName: 'Kontoname',
    openingBalance: 'Anfangssaldo',
    deleteAccountHint: 'Löscht auch alle Buchungen dieses Kontos.',
    noAccounts: 'Noch keine Konten.',
    addCategory: 'Kategorie hinzufügen',
    editCategory: 'Kategorie bearbeiten',
    categoryName: 'Name',
    expenseCategories: 'Ausgabenkategorien',
    incomeCategories: 'Einnahmenkategorien',
    deleteCategoryHint: 'Buchungen bleiben erhalten und zeigen „Ohne Kategorie“.',
    tooltipTotal: 'Gesamt',
  },
  example: {
    addPlaceholder: 'Neuer Eintrag …',
    empty: 'Noch keine Einträge.',
  },
} as const;
