/** All user-facing German UI text lives here (i18n-ready later). */
export const t = {
  appName: 'Taschenmesser',
  nav: {
    dashboard: 'Übersicht',
    library: 'Modul-Bibliothek',
    settings: 'Einstellungen',
    more: 'Mehr',
    main: 'Hauptnavigation',
    skipToContent: 'Zum Inhalt springen',
  },
  actions: {
    add: 'Hinzufügen',
    quickAdd: 'Schnell hinzufügen',
    search: 'Suchen',
    cancel: 'Abbrechen',
    save: 'Speichern',
    delete: 'Löschen',
    edit: 'Bearbeiten',
    close: 'Schließen',
    enable: 'Aktivieren',
    disable: 'Deaktivieren',
    reload: 'Neu laden',
    update: 'Aktualisieren',
  },
  dashboard: {
    title: 'Übersicht',
    emptyTitle: 'Noch keine Module aktiv',
    emptyText: 'Aktiviere Module in der Bibliothek, um hier Widgets zu sehen.',
    toLibrary: 'Zur Bibliothek',
    noWidgets: 'Die aktiven Module bieten keine Widgets an.',
  },
  library: {
    title: 'Modul-Bibliothek',
    intro: 'Aktiviere nur, was du brauchst. Deaktivierte Module bleiben unsichtbar.',
    active: 'Aktiv',
    inactive: 'Inaktiv',
    disableTitle: (name: string) => `„${name}“ deaktivieren?`,
    disableText: 'Was soll mit den gespeicherten Daten dieses Moduls passieren?',
    keepData: 'Daten behalten (ausgeblendet)',
    keepDataHint: 'Bei erneutem Aktivieren ist alles wieder da.',
    deleteData: 'Daten löschen',
    deleteDataHint: 'Alle Einträge dieses Moduls werden entfernt.',
    devOnly: 'Entwickler',
  },
  settings: {
    title: 'Einstellungen',
    appearance: 'Darstellung',
    theme: 'Farbschema',
    themeSystem: 'System',
    themeLight: 'Hell',
    themeDark: 'Dunkel',
    modules: 'Module',
    noModuleSettings: 'Aktive Module haben keine eigenen Einstellungen.',
  },
  palette: {
    title: 'Befehlspalette',
    placeholder: 'Suchen, springen oder fragen …',
    empty: 'Keine Treffer',
    hint: 'Ctrl+K',
  },
  quickAdd: {
    title: 'Schnell hinzufügen',
    empty: 'Aktive Module bieten noch keine Schnellaktionen an.',
  },
  pwa: {
    updateAvailable: 'Eine neue Version ist verfügbar.',
    offlineReady: 'Bereit für die Offline-Nutzung.',
  },
  errors: {
    notFound: 'Seite nicht gefunden',
    moduleDisabled: 'Dieses Modul ist nicht aktiv.',
    generic: 'Etwas ist schiefgelaufen.',
  },
  form: {
    title: 'Titel',
    note: 'Notiz',
    date: 'Datum',
    time: 'Uhrzeit',
    required: 'Bitte ausfüllen',
    confirmDelete: 'Wirklich löschen?',
  },
  recurrence: {
    label: 'Wiederholung',
    none: 'Keine',
    daily: 'Täglich',
    weekly: 'Wöchentlich',
    monthly: 'Monatlich',
    yearly: 'Jährlich',
    every: 'Alle',
    daysUnit: 'Tage',
    weeksUnit: 'Wochen',
    monthsUnit: 'Monate',
    yearsUnit: 'Jahre',
    weekdays: 'Wochentage',
    monthDay: 'Tag des Monats',
    lastDay: 'Letzter Tag',
    ends: 'Ende',
    endsNever: 'Nie',
    endsOn: 'Am Datum',
    endsAfter: 'Nach Anzahl',
    endDate: 'Enddatum',
    count: 'Anzahl',
  },
  todos: {
    title: 'ToDos',
    add: 'ToDo hinzufügen',
    addPlaceholder: 'Neue Aufgabe …',
    empty: 'Nichts zu tun – gut so.',
    allOpen: 'Alle offenen',
    newList: 'Neue Liste',
    listName: 'Listenname',
    renameList: 'Liste umbenennen',
    deleteList: 'Liste löschen',
    deleteListHint: 'Die Liste und alle ihre Aufgaben werden gelöscht.',
    inbox: 'Eingang',
    list: 'Liste',
    priority: 'Priorität',
    prio: ['Keine', 'Niedrig', 'Mittel', 'Hoch'],
    due: 'Fällig am',
    noDue: 'Ohne Datum',
    subtasks: 'Unteraufgaben',
    addSubtask: 'Unteraufgabe hinzufügen',
    editTask: 'Aufgabe bearbeiten',
    showDone: 'Erledigte anzeigen',
    overdue: 'Überfällig',
    openCount: (n: number) => (n === 1 ? '1 offene Aufgabe' : `${n} offene Aufgaben`),
    widgetEmpty: 'Keine offenen Aufgaben',
    progress: (done: number, total: number) => `${done}/${total}`,
  },
  calendar: {
    title: 'Kalender',
    today: 'Heute',
    month: 'Monat',
    week: 'Woche',
    day: 'Tag',
    view: 'Ansicht',
    prev: 'Zurück',
    next: 'Weiter',
    newEvent: 'Neuer Termin',
    editEvent: 'Termin bearbeiten',
    allDay: 'Ganztägig',
    start: 'Beginn',
    end: 'Ende',
    location: 'Ort',
    nothing: 'Keine Einträge',
    endBeforeStart: 'Das Ende darf nicht vor dem Beginn liegen.',
    more: (n: number) => `+${n} weitere`,
    widgetTitle: 'Heute & Morgen',
    widgetEmpty: 'Nichts geplant.',
    week_: (n: number) => `KW ${n}`,
    kinds: {
      event: 'Termin',
      task: 'ToDo',
      reminder: 'Erinnerung',
      invoice: 'Rechnung',
      subscription: 'Abo',
      cancel: 'Kündigung',
    } as Record<string, string>,
  },
  reminders: {
    title: 'Erinnerungen',
    add: 'Erinnerung hinzufügen',
    edit: 'Erinnerung bearbeiten',
    empty: 'Noch keine Erinnerungen.',
    firstDate: 'Erster Termin',
    next: 'Nächste',
    ended: 'Beendet',
    paused: 'Pausiert',
    active: 'Aktiv',
    widgetTitle: 'Nächste Erinnerungen',
    widgetEmpty: 'Keine anstehenden Erinnerungen.',
  },
  notifications: {
    title: 'Benachrichtigungen',
    intro:
      'Erinnerungen erscheinen als Benachrichtigung, solange die App geöffnet ist oder im Hintergrund läuft. Bei geschlossener App kommen sie nur mit Push (siehe unten).',
    enable: 'Benachrichtigungen aktivieren',
    granted: 'Aktiviert',
    denied: 'Blockiert – bitte in den Browser-Einstellungen für diese Seite erlauben.',
    default: 'Noch nicht aktiviert',
    unsupported: 'Wird von diesem Browser nicht unterstützt.',
    test: 'Testbenachrichtigung senden',
    testBody: 'Es funktioniert.',
    push: {
      title: 'Push bei geschlossener App',
      intro:
        'Optional: Dein Sync-Server schickt Erinnerungen per Web Push, auch wenn die App geschlossen ist. Dafür lädt die App die anstehenden Benachrichtigungen der nächsten zwei Wochen (Titel und Text) zu deinem Server hoch – mit Ende-zu-Ende-Verschlüsselung nur verschlüsselt.',
      state: {
        unsupported: 'Dieser Browser unterstützt kein Web Push.',
        'needs-sync':
          'Push braucht die Verbindung zu deinem Sync-Server (Einstellungen → Synchronisation).',
        denied: 'Benachrichtigungen sind blockiert – bitte in den Browser-Einstellungen erlauben.',
        off: 'Aus',
        on: 'Aktiv auf diesem Gerät',
      } as Record<string, string>,
      enable: 'Push aktivieren',
      disable: 'Push deaktivieren',
      test: 'Test über den Server senden',
      testSent: 'Gesendet – die Benachrichtigung sollte gleich erscheinen.',
      testFailed: 'Der Server konnte nicht senden (Push-Dienst nicht erreichbar?).',
      errors: {
        unauthorized: 'Das Token des Sync-Servers wurde abgelehnt.',
        network: 'Der Sync-Server ist nicht erreichbar.',
        server: 'Der Sync-Server hat einen Fehler gemeldet (ist er auf dem neuesten Stand?).',
        'subscribe-failed':
          'Das Abonnement konnte nicht angelegt werden. Push braucht HTTPS und einen Browser mit Push-Dienst.',
        denied: 'Benachrichtigungen wurden nicht erlaubt.',
        unsupported: 'Dieser Browser unterstützt kein Web Push.',
        'needs-sync': 'Bitte zuerst mit dem Sync-Server verbinden.',
      } as Record<string, string>,
    },
  },
  dashboardEdit: {
    customize: 'Anpassen',
    done: 'Fertig',
    hide: 'Ausblenden',
    show: 'Einblenden',
    handle: (title: string) => `${title} verschieben`,
    hidden: 'Ausgeblendet',
    instructions:
      'Zum Verschieben Leertaste drücken, mit den Pfeiltasten bewegen und mit der Leertaste ablegen. Esc bricht ab.',
    picked: (title: string) => `${title} aufgenommen.`,
    moved: (title: string, pos: number) => `${title} auf Position ${pos} verschoben.`,
    dropped: (title: string, pos: number) => `${title} auf Position ${pos} abgelegt.`,
    cancelled: 'Verschieben abgebrochen.',
  },
  money: {
    amount: 'Betrag',
    invalidAmount: 'Bitte einen gültigen Betrag eingeben, z. B. 12,50',
  },
  invoices: {
    title: 'Rechnungen',
    add: 'Rechnung hinzufügen',
    edit: 'Rechnung bearbeiten',
    payee: 'Empfänger',
    reference: 'Verwendungszweck / Rechnungsnummer',
    dueDate: 'Fällig am',
    paidAt: 'Bezahlt am',
    open: 'Offen',
    paid: 'Bezahlt',
    markPaid: 'Als bezahlt markieren',
    markedPaid: 'Als bezahlt markiert.',
    reopen: 'Wieder öffnen',
    undo: 'Rückgängig',
    empty: 'Keine offenen Rechnungen.',
    emptyPaid: 'Noch keine bezahlten Rechnungen.',
    openTotal: 'Offen gesamt',
    overdue: 'Überfällig',
    widgetEmpty: 'Keine offenen Rechnungen.',
    openCount: (n: number) => (n === 1 ? '1 offene Rechnung' : `${n} offene Rechnungen`),
    view: 'Status',
  },
  subscriptions: {
    title: 'Abos',
    add: 'Abo hinzufügen',
    edit: 'Abo bearbeiten',
    name: 'Name',
    firstCharge: 'Abbuchung am',
    firstChargeHint: 'Ein bekanntes Abbuchungsdatum – daraus ergeben sich die weiteren.',
    noticeDays: 'Kündigungsfrist (Tage vor Abbuchung)',
    noticeHint: 'Leer lassen, wenn jederzeit kündbar.',
    active: 'Aktiv',
    paused: 'Pausiert',
    empty: 'Noch keine Abos.',
    perMonth: 'Pro Monat',
    perYear: 'Pro Jahr',
    perMonthShort: 'pro Monat',
    nextCharge: 'Nächste Abbuchung',
    cancelBy: 'Kündigen bis',
    ended: 'Beendet',
    every: 'Intervall',
    widgetEmpty: 'Keine aktiven Abos.',
    monthlyCost: (v: string) => `≙ ${v} pro Monat`,
  },
  finance: {
    title: 'Finanzen',
    balance: 'Kontostand',
    available: 'Verfügbar',
    tabs: {
      overview: 'Übersicht',
      transactions: 'Buchungen',
      accounts: 'Konten',
      categories: 'Kategorien',
    },
    tabsLabel: 'Bereich',
    month: 'Monat',
    currentMonth: 'Aktueller Monat',
    prevMonth: 'Vorheriger Monat',
    nextMonth: 'Nächster Monat',
    income: 'Einnahmen',
    expense: 'Ausgaben',
    net: 'Saldo',
    incomeOne: 'Einnahme',
    expenseOne: 'Ausgabe',
    kind: 'Art',
    breakdown: (balance: string, invoices: string, subs: string) =>
      [
        `Kontostand ${balance}`,
        invoices && `offene Rechnungen −${invoices}`,
        subs && `Abos bis Monatsende −${subs}`,
      ]
        .filter(Boolean)
        .join(' · '),
    expensesByCategory: 'Ausgaben nach Kategorie',
    trend: 'Einnahmen und Ausgaben der letzten 6 Monate',
    showTable: 'Als Tabelle anzeigen',
    showChart: 'Als Diagramm anzeigen',
    tableShort: 'Tabelle',
    chartShort: 'Diagramm',
    addTransactionShort: 'Buchung',
    noExpenses: 'Keine Ausgaben in diesem Monat.',
    category: 'Kategorie',
    amount: 'Betrag',
    month_: 'Monat',
    addTransaction: 'Buchung hinzufügen',
    editTransaction: 'Buchung bearbeiten',
    noTransactions: 'Keine Buchungen in diesem Monat.',
    payee: 'Empfänger / Titel',
    account: 'Konto',
    noCategory: 'Ohne Kategorie',
    fromInvoice: 'Automatisch aus einer bezahlten Rechnung gebucht.',
    addAccount: 'Konto hinzufügen',
    editAccount: 'Konto bearbeiten',
    accountName: 'Kontoname',
    openingBalance: 'Anfangssaldo',
    deleteAccountHint: 'Löscht auch alle Buchungen dieses Kontos.',
    noAccounts: 'Noch keine Konten.',
    addCategory: 'Kategorie hinzufügen',
    editCategory: 'Kategorie bearbeiten',
    categoryName: 'Name',
    expenseCategories: 'Ausgabenkategorien',
    incomeCategories: 'Einnahmenkategorien',
    deleteCategoryHint: 'Buchungen bleiben erhalten und zeigen „Ohne Kategorie“.',
    tooltipTotal: 'Gesamt',
  },
  sync: {
    title: 'Synchronisation',
    intro:
      'Optional: gleiche deine Daten über deinen eigenen Sync-Server ab (im LAN oder über Tailscale). Ohne Server bleibt alles lokal auf diesem Gerät.',
    serverUrl: 'Server-Adresse',
    serverUrlHint: 'z. B. https://mein-pc.tailnet.ts.net',
    token: 'Zugangstoken',
    encrypt: 'Ende-zu-Ende-Verschlüsselung',
    encryptHint:
      'Werte werden auf dem Gerät verschlüsselt, der Server sieht nur Chiffretext. Nur auf einem leeren Server möglich.',
    passphrase: 'Passphrase',
    passphraseHint:
      'Mindestens 8 Zeichen. Ohne die Passphrase sind die Daten nicht wiederherstellbar.',
    passphraseJoinHint: 'Nur nötig, wenn der Server verschlüsselt ist.',
    connect: 'Verbinden',
    connecting: 'Verbinde …',
    connected: (host: string) => `Verbunden mit ${host}`,
    encryptedBadge: 'Verschlüsselt',
    plainBadge: 'Unverschlüsselt',
    lastSync: 'Zuletzt synchronisiert',
    never: 'noch nicht',
    pending: (n: number) =>
      n === 0 ? 'Alles gesendet' : n === 1 ? '1 Änderung wartet' : `${n} Änderungen warten`,
    syncNow: 'Jetzt synchronisieren',
    disconnect: 'Trennen',
    disconnectHint: 'Deine lokalen Daten bleiben erhalten; der Server wird nicht verändert.',
    state: { off: 'Aus', idle: 'Synchronisiert', syncing: 'Synchronisiere …', error: 'Fehler' },
    badge: (state: string) => `Synchronisation: ${state}`,
    errors: {
      network: 'Server nicht erreichbar.',
      unauthorized: 'Der Server hat das Token abgelehnt.',
      server: 'Der Server hat einen Fehler gemeldet.',
      decrypt: 'Entschlüsselung fehlgeschlagen – stimmt die Passphrase?',
      'no-key':
        'Die Daten auf dem Server sind verschlüsselt. Bitte trennen und neu mit Passphrase verbinden.',
      unsupported: 'Nicht unterstützt.',
      unknown: 'Unbekannter Fehler.',
    } as Record<string, string>,
    failures: {
      'invalid-url': 'Bitte eine gültige Adresse mit http:// oder https:// eingeben.',
      unreachable:
        'Server nicht erreichbar. Wird die App per HTTPS geöffnet, muss auch der Server per HTTPS erreichbar sein (z. B. mit „tailscale serve“).',
      unauthorized: 'Das Token wurde abgelehnt.',
      'passphrase-required': 'Dieser Server ist verschlüsselt. Bitte die Passphrase eingeben.',
      'passphrase-too-short': 'Die Passphrase braucht mindestens 8 Zeichen.',
      'wrong-passphrase': 'Falsche Passphrase.',
      'server-has-plain-data':
        'Auf dem Server liegen bereits unverschlüsselte Daten. Verschlüsselung ist nur auf einem leeren Server möglich.',
      'server-error': 'Der Server hat einen Fehler gemeldet.',
    } as Record<string, string>,
    resetServer: 'Server zurücksetzen und verschlüsselt neu aufbauen',
    resetTitle: 'Server zurücksetzen?',
    resetText:
      'Alle Daten auf dem Server werden gelöscht. Deine lokalen Daten bleiben erhalten und werden erneut hochgeladen; andere Geräte laden ihre Daten beim nächsten Sync ebenfalls wieder hoch.',
    resetConfirm: 'Zurücksetzen',
  },
  backup: {
    title: 'Backup',
    intro:
      'Sichere alle Daten als Datei oder spiele ein Backup wieder ein. Zugangsdaten (Sync-Token, Schlüssel) sind nie im Backup enthalten.',
    export: 'Backup herunterladen',
    exported: 'Backup heruntergeladen.',
    file: 'Backup-Datei',
    mode: 'Wiederherstellung',
    merge: 'Zusammenführen',
    mergeHint: 'Es geht nichts verloren; bei Konflikten gewinnt die jeweils neuere Änderung.',
    replace: 'Ersetzen',
    replaceHint: 'Das Backup wird zum Stand: Einträge, die nicht im Backup sind, werden gelöscht.',
    doImport: 'Importieren',
    contains: (records: number, tables: number) => `${records} Einträge in ${tables} Tabellen`,
    confirmTitle: 'Backup ersetzen?',
    confirmText:
      'Alle Einträge, die nicht im Backup stehen, werden gelöscht – auch auf anderen Geräten, sobald sie synchronisieren.',
    done: (records: number, removed: number) =>
      removed > 0
        ? `${records} Einträge wiederhergestellt, ${removed} entfernt.`
        : `${records} Einträge wiederhergestellt.`,
    errors: {
      'not-json': 'Die Datei ist keine gültige JSON-Datei.',
      'wrong-format': 'Das ist keine Taschenmesser-Backup-Datei.',
      'newer-version': 'Das Backup stammt aus einer neueren App-Version.',
      invalid: 'Die Backup-Datei ist beschädigt.',
    } as Record<string, string>,
  },
  ai: {
    title: 'KI-Assistent',
    yes: 'Ja',
    no: 'Nein',
    untitled: '(ohne Titel)',
    fieldLabels: {
      title: 'Titel',
      name: 'Name',
      done: 'Erledigt',
      priority: 'Priorität',
      dueDate: 'Fällig',
      note: 'Notiz',
      startDate: 'Datum',
      startTime: 'Uhrzeit',
      time: 'Uhrzeit',
      location: 'Ort',
      recurrence: 'Wiederholung',
      active: 'Aktiv',
      payee: 'Empfänger',
      amountMinor: 'Betrag',
      status: 'Status',
      paidAt: 'Bezahlt am',
      cancelNoticeDays: 'Kündigungsfrist (Tage)',
      openingBalanceMinor: 'Anfangssaldo',
      kind: 'Art',
      date: 'Datum',
    } as Record<string, string>,
    enumValues: {
      open: 'offen',
      paid: 'bezahlt',
      expense: 'Ausgabe',
      income: 'Einnahme',
    } as Record<string, string>,
    countNote: (n: number) => (n === 1 ? '1 Eintrag' : `${n} Einträge`),
    sumNote: (field: string, n: number) => `${field}, ${n === 1 ? '1 Eintrag' : `${n} Einträge`}`,
    searchHeading: (text: string) => `Treffer für „${text}“`,
    computed: {
      openInvoices: 'Offene Rechnungen',
      subsUntilMonthEnd: 'Abos bis Monatsende',
      activeSubs: 'Aktive Abos',
      perMonth: 'Pro Monat',
      perYear: 'Pro Jahr',
      openCount: 'Offene Rechnungen',
      openTotal: 'Summe offen',
      nextDue: 'Nächste Fälligkeit',
    },
    palette: {
      askModel: 'Mit KI fragen',
      askModelHint: 'Die Frage geht an das eingerichtete Modell (ohne deine Daten).',
      thinking: 'Ich überlege …',
      back: 'Zurück',
      answer: 'Antwort',
      noResults: 'Keine Treffer.',
      more: (n: number) => `… und ${n} weitere`,
      agendaEmpty: 'In diesem Zeitraum steht nichts an.',
      agendaRange: (from: string, to: string) => (from === to ? from : `${from} – ${to}`),
      noModelHint:
        'Für komplexere Fragen kannst du unter Einstellungen → KI-Assistent ein Modell einrichten.',
      searchHits: 'Gefunden',
      ask: 'Assistent fragen',
    },
    tier: {
      local: 'Lokal · 0 Token',
      cache: 'Aus dem Cache · 0 Token',
      model: (input: number, output: number) => `KI · ${input} + ${output} Token`,
    },
    create: {
      title: (label: string) => `${label} anlegen?`,
      intro:
        'Der Assistent schlägt diesen Eintrag vor. Es wird erst etwas gespeichert, wenn du bestätigst.',
      confirm: 'Anlegen',
      cancel: 'Abbrechen',
      done: (label: string) => `${label} angelegt.`,
      failed: 'Der Eintrag konnte nicht gespeichert werden.',
    },
    errors: {
      auth: 'Der API-Schlüssel wurde abgelehnt. Bitte prüfe ihn in den Einstellungen.',
      'rate-limit': 'Zu viele Anfragen – bitte in einer Minute noch einmal versuchen.',
      network: 'Keine Verbindung zum KI-Dienst. Bist du online?',
      'bad-request': 'Der KI-Dienst hat die Anfrage abgelehnt.',
      server: 'Der KI-Dienst hat gerade ein Problem. Bitte später noch einmal versuchen.',
      refusal: 'Dazu kann das Modell nichts sagen.',
      aborted: 'Abgebrochen.',
      unavailable:
        'Das lokale Modell ist nicht erreichbar. Läuft Ollama und ist OLLAMA_ORIGINS gesetzt?',
      'not-configured': 'Es ist noch kein KI-Modell eingerichtet (Einstellungen → KI-Assistent).',
      'inactive-module': 'Dafür muss das passende Modul aktiviert sein (Modul-Bibliothek).',
      'invalid-entry':
        'Die Angaben reichen für einen Eintrag nicht aus. Nenne z. B. Titel und Datum genauer.',
      'invalid-answer': 'Die Antwort des Modells war nicht brauchbar. Bitte anders formulieren.',
      'no-answer': 'Dazu habe ich keine Antwort.',
      fallback: 'Diese Frage konnte ich nicht sicher zuordnen. Bitte anders formulieren.',
    } as Record<string, string>,
    settings: {
      intro:
        'Fragen wie „Was steht morgen an?“ beantwortet die App lokal und ohne Kosten. Nur für schwierigere Fragen kann sie ein KI-Modell fragen.',
      privacy:
        'Datenschutz: An das Modell gehen nur deine Frage, das heutige Datum und die kurze Beschreibung der aktiven Module – niemals deine Daten. Die Antwort wird lokal berechnet.',
      provider: 'Modell',
      providerOff: 'Aus (nur lokale Suche)',
      providerClaude: 'Claude (Anthropic)',
      providerOllama: 'Ollama (lokal)',
      apiKey: 'API-Schlüssel',
      apiKeyHint:
        'Wird nur auf diesem Gerät gespeichert (nicht synchronisiert, nicht im Backup) und direkt aus dem Browser an Anthropic gesendet.',
      claudeModel: 'Modell',
      claudeModelHint: 'Standard ist das günstige Claude Haiku 4.5.',
      ollamaUrl: 'Ollama-Adresse',
      ollamaModel: 'Ollama-Modell',
      ollamaHint:
        'Ollama muss Anfragen dieser App erlauben, z. B. mit OLLAMA_ORIGINS=* (siehe README). Das Modell muss Tool-Aufrufe unterstützen.',
      save: 'Speichern',
      saved: 'Gespeichert.',
      usageTitle: 'Verbrauch',
      usageEmpty: 'Noch keine KI-Anfragen.',
      usageRequests: (n: number) => (n === 1 ? '1 KI-Anfrage' : `${n} KI-Anfragen`),
      usageCacheHits: (n: number) =>
        n === 1 ? '1 Antwort aus dem Cache' : `${n} Antworten aus dem Cache`,
      usageTokens: (input: number, output: number) =>
        `${input} Token gesendet, ${output} empfangen`,
      usageCost: (usd: string) => `ca. ${usd} US-Dollar`,
      usageReset: 'Zähler zurücksetzen',
      clearCache: 'Cache leeren',
      cacheCleared: 'Cache geleert.',
    },
  },
  bookmarks: {
    title: 'Merkliste',
    add: 'Merken',
    edit: 'Merkzettel bearbeiten',
    url: 'Adresse (Link)',
    urlInvalid: 'Bitte eine gültige http(s)-Adresse eingeben.',
    kind: 'Art',
    kinds: {
      link: 'Link',
      read: 'Lesen',
      watch: 'Ansehen',
      place: 'Ort',
      idea: 'Idee',
      other: 'Sonstiges',
    } as Record<string, string>,
    allKinds: 'Alle Arten',
    tags: 'Tags',
    tagsHint: 'Mit Komma trennen, z. B. Rezept, Urlaub',
    filterTags: 'Nach Tag filtern',
    search: 'Merkliste durchsuchen',
    view: 'Status',
    views: { open: 'Offen', done: 'Erledigt', all: 'Alle' },
    empty: 'Noch nichts gemerkt.',
    emptyFiltered: 'Nichts gefunden.',
    open: 'Link öffnen',
    done: 'Erledigt',
    widgetEmpty: 'Nichts gemerkt.',
    openCount: (n: number) => (n === 1 ? '1 offener Merkzettel' : `${n} offene Merkzettel`),
  },
  notes: {
    title: 'Notizen',
    add: 'Notiz hinzufügen',
    edit: 'Notiz bearbeiten',
    body: 'Text',
    pin: 'Oben anheften',
    search: 'Notizen durchsuchen',
    empty: 'Noch keine Notizen.',
    emptyFiltered: 'Nichts gefunden.',
    widgetEmpty: 'Noch keine Notizen.',
  },
  shopping: {
    title: 'Einkaufsliste',
    addLabel: 'Artikel hinzufügen',
    placeholder: 'z. B. 2 Milch',
    empty: 'Die Einkaufsliste ist leer.',
    clearBought: (n: number) => `Gekauftes entfernen (${n})`,
    cleared: (n: number) => (n === 1 ? '1 Artikel entfernt.' : `${n} Artikel entfernt.`),
    widgetEmpty: 'Nichts einzukaufen.',
    openCount: (n: number) => (n === 1 ? '1 Artikel offen' : `${n} Artikel offen`),
  },
  birthdays: {
    title: 'Geburtstage',
    add: 'Geburtstag hinzufügen',
    edit: 'Geburtstag bearbeiten',
    name: 'Name',
    date: 'Geburtsdatum',
    yearUnknown: 'Geburtsjahr unbekannt',
    invalidDate: 'Bitte ein gültiges Datum eingeben.',
    turns: (age: number) => `wird ${age}`,
    empty: 'Noch keine Geburtstage.',
    widgetEmpty: 'Noch keine Geburtstage.',
  },
  habits: {
    title: 'Habit-Tracker',
    add: 'Gewohnheit hinzufügen',
    edit: 'Gewohnheit bearbeiten',
    name: 'Name',
    weekdays: 'An diesen Tagen',
    dayNames: ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'],
    needDay: 'Bitte mindestens einen Tag wählen.',
    archive: 'Archivieren (ausblenden, Verlauf bleibt)',
    archived: 'archiviert',
    showArchived: 'Archivierte anzeigen',
    hideArchived: 'Archivierte ausblenden',
    lastDays: 'Letzte Tage',
    streak: (n: number) => (n === 1 ? '1 Tag in Folge' : `${n} Tage in Folge`),
    rate: (pct: number) => `${pct} % in 30 Tagen`,
    empty: 'Noch keine Gewohnheiten.',
    widgetEmpty: 'Heute nichts vorgesehen.',
    todayDone: (done: number, total: number) => `${done} von ${total} erledigt`,
  },
  contracts: {
    title: 'Verträge & Garantien',
    add: 'Vertrag hinzufügen',
    edit: 'Vertrag bearbeiten',
    name: 'Bezeichnung',
    kind: 'Art',
    kinds: { contract: 'Vertrag', insurance: 'Versicherung', warranty: 'Garantie' } as Record<
      string,
      string
    >,
    provider: 'Anbieter',
    startDate: 'Beginn',
    endDate: 'Ende / Ablauf',
    noticeDays: 'Kündigungsfrist (Tage vor Ende)',
    noticeHint: 'Leer lassen, wenn es keine Frist gibt (z. B. bei Garantien).',
    invalid: 'Bitte die Angaben prüfen (das Ende darf nicht vor dem Beginn liegen).',
    endLabel: 'Ende',
    deadlineLabel: 'Kündigen bis',
    status: {
      expired: 'Abgelaufen',
      'act-now': 'Jetzt kündigen',
      soon: 'Bald',
      ok: '',
      'open-ended': '',
    } as Record<string, string>,
    endsOn: (name: string, kind: string) =>
      kind === 'warranty' ? `Garantie endet: ${name}` : `Vertragsende: ${name}`,
    cancelBy: (name: string) => `Kündigungsfrist: ${name}`,
    remindBody: (date: string) => `Am ${date.split('-').reverse().join('.')}`,
    empty: 'Noch keine Verträge oder Garantien.',
    widgetEmpty: 'Keine Fristen in Sicht.',
  },
  budgets: {
    title: 'Budgets & Sparziele',
    tabs: 'Bereich',
    tabBudgets: 'Budgets',
    tabGoals: 'Sparziele',
    addBudget: 'Budget hinzufügen',
    editBudget: 'Budget bearbeiten',
    addGoal: 'Sparziel hinzufügen',
    editGoal: 'Sparziel bearbeiten',
    category: 'Kategorie',
    unknownCategory: 'Gelöschte Kategorie',
    limit: 'Limit pro Monat',
    needFinance: 'Budgets brauchen das Modul „Finanzen“.',
    needFinanceHint:
      'Aktiviere es in der Modul-Bibliothek – die Ausgaben je Kategorie kommen von dort.',
    prevMonth: 'Vorheriger Monat',
    nextMonth: 'Nächster Monat',
    emptyBudgets: 'Noch keine Budgets. Lege ein Monatslimit für eine Ausgabenkategorie fest.',
    emptyGoals: 'Noch keine Sparziele.',
    spentOf: (spent: string, limit: string) => `${spent} von ${limit}`,
    left: (amount: string) => `noch ${amount}`,
    over: (amount: string) => `${amount} drüber`,
    goalName: 'Wofür sparst du?',
    target: 'Zielbetrag',
    deadline: 'Bis (optional)',
    until: (date: string) => `bis ${date}`,
    remaining: 'Fehlt noch',
    reached: 'Erreicht',
    perMonth: (amount: string) => `Bis zur Frist: ${amount} pro Monat zurücklegen`,
    deposit: 'Einzahlen',
    depositTitle: (name: string) => `Einzahlung: ${name}`,
    depositIn: 'Einzahlung',
    depositOut: 'Entnahme',
    kind: 'Art',
    history: 'Verlauf',
    historyTitle: (name: string) => `Verlauf: ${name}`,
    noDeposits: 'Noch keine Einzahlungen.',
    widgetEmpty: 'Nichts zu beachten.',
  },
  packing: {
    title: 'Packlisten',
    lists: 'Listen',
    addList: 'Liste hinzufügen',
    editList: 'Liste bearbeiten',
    listName: 'Name der Liste',
    addItem: 'Gegenstand hinzufügen',
    itemPlaceholder: 'z. B. Sonnencreme',
    progress: (packed: number, total: number) => `${packed} von ${total} gepackt`,
    complete: 'Alles gepackt!',
    reset: 'Alles auspacken',
    duplicate: 'Als Vorlage kopieren',
    copied: 'Liste kopiert.',
    empty: 'Noch keine Packlisten.',
    widgetEmpty: 'Nichts zu packen.',
  },
  vault: {
    title: 'Dokumente',
    add: 'Dokument hinzufügen',
    edit: 'Dokument bearbeiten',
    category: 'Kategorie',
    allCategories: 'Alle',
    categories: {
      identity: 'Ausweise',
      insurance: 'Versicherung',
      contract: 'Verträge',
      tax: 'Steuer',
      health: 'Gesundheit',
      other: 'Sonstiges',
    } as Record<string, string>,
    expiresOn: 'Läuft ab am',
    expiresTitle: (title: string) => `Läuft ab: ${title}`,
    remindBody: (date: string) => `Gültig bis ${date.split('-').reverse().join('.')}`,
    file: 'Datei',
    localOnly:
      'Dateien bleiben nur auf diesem Gerät: Sie werden weder synchronisiert noch ins Backup geschrieben. Titel, Ablaufdatum und Notizen werden wie üblich synchronisiert.',
    fileElsewhere: 'Datei nur auf einem anderen Gerät',
    removeFile: 'Datei entfernen',
    tooLarge: (max: string) => `Die Datei ist zu groß (höchstens ${max}).`,
    download: 'Herunterladen',
    search: 'Dokumente durchsuchen',
    expired: 'Abgelaufen',
    soon: 'Läuft bald ab',
    empty: 'Noch keine Dokumente.',
    emptyFiltered: 'Nichts gefunden.',
    widgetEmpty: 'Nichts läuft bald ab.',
  },
  update: {
    title: 'App-Updates',
    available: (version: string) => `Update verfügbar (v${version})`,
    beta: 'Beta',
    whatsNew: 'Was ist neu?',
    updateNow: 'Jetzt aktualisieren',
    later: 'Später',
    backingUp: 'Sicherungskopie deiner Daten wird angelegt …',
    downloading: 'Update wird heruntergeladen …',
    downloadingPercent: (pct: number) => `Update wird heruntergeladen … ${pct} %`,
    handover: 'Fast fertig – die App startet gleich neu bzw. Android öffnet die Installation.',
    needsPermission:
      'Android braucht noch deine Erlaubnis, Apps aus dieser Quelle zu installieren. Aktiviere den Schalter in den Einstellungen und tippe danach erneut auf „Jetzt aktualisieren“.',
    retry: 'Erneut versuchen',
    errors: {
      'check-failed': 'Die Suche nach Updates ist fehlgeschlagen. Bist du online?',
      'backup-failed':
        'Die Sicherungskopie konnte nicht angelegt werden – das Update wurde deshalb nicht gestartet.',
      'install-failed': 'Das Update konnte nicht installiert werden.',
    } as Record<string, string>,
    settings: {
      intro:
        'Die installierte App prüft auf GitHub, ob es eine neue Version gibt. Vor jedem Update legt sie automatisch eine Sicherungskopie deiner Daten an.',
      version: 'Installierte Version',
      channel: 'Update-Kanal',
      channelStable: 'Stabil',
      channelBeta: 'Beta (auch Vorabversionen)',
      auto: 'Automatisch nach Updates suchen',
      autoHint: 'Höchstens einmal täglich, beim Start der App.',
      checkNow: 'Jetzt prüfen',
      checking: 'Suche nach Updates …',
      upToDate: 'Du hast die neueste Version.',
      browserHint:
        'Im Browser aktualisiert sich die App selbst (Hinweis oben nach dem Laden einer neuen Version).',
    },
  },
  example: {
    addPlaceholder: 'Neuer Eintrag …',
    empty: 'Noch keine Einträge.',
  },
} as const;
