/** All user-facing German UI text lives here (i18n-ready later). */
export const t = {
  appName: 'Taschenmesser',
  nav: {
    dashboard: 'Übersicht',
    library: 'Modul-Bibliothek',
    settings: 'Einstellungen',
    more: 'Mehr',
    main: 'Hauptnavigation',
    skipToContent: 'Zum Inhalt springen',
  },
  actions: {
    add: 'Hinzufügen',
    quickAdd: 'Schnell hinzufügen',
    search: 'Suchen',
    cancel: 'Abbrechen',
    save: 'Speichern',
    delete: 'Löschen',
    edit: 'Bearbeiten',
    close: 'Schließen',
    enable: 'Aktivieren',
    disable: 'Deaktivieren',
    reload: 'Neu laden',
    update: 'Aktualisieren',
  },
  dashboard: {
    title: 'Übersicht',
    emptyTitle: 'Noch keine Module aktiv',
    emptyText: 'Aktiviere Module in der Bibliothek, um hier Widgets zu sehen.',
    toLibrary: 'Zur Bibliothek',
    noWidgets: 'Die aktiven Module bieten keine Widgets an.',
  },
  library: {
    title: 'Modul-Bibliothek',
    intro: 'Aktiviere nur, was du brauchst. Deaktivierte Module bleiben unsichtbar.',
    active: 'Aktiv',
    inactive: 'Inaktiv',
    disableTitle: (name: string) => `„${name}“ deaktivieren?`,
    disableText: 'Was soll mit den gespeicherten Daten dieses Moduls passieren?',
    keepData: 'Daten behalten (ausgeblendet)',
    keepDataHint: 'Bei erneutem Aktivieren ist alles wieder da.',
    deleteData: 'Daten löschen',
    deleteDataHint: 'Alle Einträge dieses Moduls werden entfernt.',
    devOnly: 'Entwickler',
  },
  settings: {
    title: 'Einstellungen',
    appearance: 'Darstellung',
    theme: 'Farbschema',
    themeSystem: 'System',
    themeLight: 'Hell',
    themeDark: 'Dunkel',
    modules: 'Module',
    noModuleSettings: 'Aktive Module haben keine eigenen Einstellungen.',
  },
  palette: {
    title: 'Befehlspalette',
    placeholder: 'Suchen oder springen zu …',
    empty: 'Keine Treffer',
    hint: 'Ctrl+K',
  },
  quickAdd: {
    title: 'Schnell hinzufügen',
    empty: 'Aktive Module bieten noch keine Schnellaktionen an.',
  },
  pwa: {
    updateAvailable: 'Eine neue Version ist verfügbar.',
    offlineReady: 'Bereit für die Offline-Nutzung.',
  },
  errors: {
    notFound: 'Seite nicht gefunden',
    moduleDisabled: 'Dieses Modul ist nicht aktiv.',
    generic: 'Etwas ist schiefgelaufen.',
  },
  example: {
    addPlaceholder: 'Neuer Eintrag …',
    empty: 'Noch keine Einträge.',
  },
} as const;
