/** German words the rule parser reacts to. All entries are folded (lowercase, no umlauts, ß → ss). */

/** The sentence starts like a search or a question – never a write. Prefixes of longer verbs … */
const SEARCH_PREFIXES = [
  'zeig',
  'such',
  'find',
  'anzeig',
  'offne',
  'oeffne',
  'berechne',
  'wieviel',
  'welch',
  'liste',
  'ubersicht',
];
/** … and whole words (a prefix "wo" would also catch "Wohnung", "was" would catch "waschen"). */
const SEARCH_WORDS = ['wie', 'was', 'wo', 'wer', 'wann', 'wem', 'wen', 'warum', 'wieso', 'gibt'];
export const isSearchStart = (n: string): boolean =>
  SEARCH_WORDS.includes(n) || SEARCH_PREFIXES.some((p) => n.startsWith(p));

/** Polite padding in front of the real verb. */
export const POLITE = [
  'bitte',
  'kannst',
  'konntest',
  'konnte',
  'du',
  'ich',
  'mochte',
  'moechte',
  'will',
  'brauche',
  'mal',
  'noch',
  'doch',
  'schnell',
  'jetzt',
  'gleich',
];

export const DELETE_VERBS = ['losch', 'loesch', 'entfern', 'streich', 'wegwerf'];
/** Prefixes of change verbs ("verschiebe", "verschieben", "verschiebt" …). */
export const UPDATE_PREFIXES = [
  'verschieb',
  'korrigier',
  'aktualisier',
  'benenne',
  'ersetz',
  'erhoh',
  'erhoeh',
  'verlanger',
];
/** Whole words only: "anderen" is not "ändere". */
export const UPDATE_WORDS = ['andere', 'aendere', 'andern', 'aendern'];
/** Whole words only: "schreiben" in "Bericht schreiben" belongs to the title. */
export const CREATE_WORDS = [
  'lege',
  'leg',
  'erstelle',
  'erstell',
  'trage',
  'trag',
  'fuge',
  'fuege',
  'notiere',
  'notier',
  'speichere',
  'speicher',
  'buche',
  'merke',
  'merk',
  'vermerke',
  'erfasse',
  'neue',
  'neuer',
  'neues',
  'neuen',
  'anlegen',
  'eintragen',
  'hinzufugen',
  'hinzufuegen',
  'add',
  'setz',
  'setze',
  'schreib',
  'schreibe',
];
/** Verbs that introduce a state change ("markiere … als bezahlt"). They carry no information. */
export const MARK_VERBS = ['markier', 'hak', 'setz', 'stell', 'mach', 'kundig', 'erledig'];

/** Words that may stay at the edges of what is left and are dropped there. */
export const EDGE_FILLERS = new Set([
  'der',
  'die',
  'das',
  'den',
  'dem',
  'des',
  'ein',
  'eine',
  'einen',
  'einem',
  'einer',
  'mein',
  'meine',
  'meinen',
  'meinem',
  'meiner',
  'von',
  'vom',
  'zu',
  'zum',
  'zur',
  'im',
  'in',
  'am',
  'an',
  'auf',
  'fur',
  'fuer',
  'als',
  'mit',
  'bei',
  'und',
  'oder',
  'bitte',
  'mir',
  'dir',
  'mich',
  'ist',
  'wird',
  'wurde',
  'sind',
  'ab',
  'bis',
  'um',
  'seit',
  'faellig',
  'fallig',
  'nach',
  'aus',
  'ein',
  'hinzu',
  'dazu',
  'neu',
  'noch',
  'mal',
  'jeden',
  'jede',
  'jedes',
  'alle',
  'pro',
  'je',
  'per',
  'zahlbar',
  'bezahlen',
  'ueber',
  'uber',
  'namens',
  'name',
  'heisst',
  'betrag',
  'datum',
  'frist',
  'lauft',
  'gultig',
  'gueltig',
  'gilt',
  'endet',
  'laeuft',
]);

export const isCreateWord = (n: string): boolean => CREATE_WORDS.includes(n);
export const isUpdateWord = (n: string): boolean =>
  UPDATE_WORDS.includes(n) || UPDATE_PREFIXES.some((p) => n.startsWith(p));
